global:
  scrape_interval: 15s  # Как часто собирать метрики

scrape_configs:
  # Собираем метрики с Traefik (если вы его настроили)
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']  # Адрес контейнера Traefik

  # Собираем метрики с вашего приложения
  - job_name: 'backend'
    metrics_path: /metrics  # Пусть до эндпоинта метрик
    static_configs:
      - targets: ['api:8000']  # Название сервиса и порт, на котором работает FastAPI
