"""empty message

Revision ID: 87329d0cb2a7
Revises: 8a5245a42bac
Create Date: 2024-09-21 19:28:06.096633

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87329d0cb2a7"
down_revision = "8a5245a42bac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("created_by", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "teams", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_column("teams", "created_by")
    # ### end Alembic commands ###
