"""empty message

Revision ID: b6e080022c8c
Revises: 81bf9874ed34
Create Date: 2024-08-31 22:59:13.199796

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6e080022c8c"
down_revision = "81bf9874ed34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_tokens")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("login", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "last_login_ip", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_login_dt", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_dt", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_dt", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint("email", name="users_email_key"),
        sa.UniqueConstraint("login", name="users_login_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_alive", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ttl_sec", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_dt", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_dt", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="refresh_tokens_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="refresh_tokens_pkey"),
    )
    # ### end Alembic commands ###
