"""empty message

Revision ID: f40098cf7022
Revises: 87329d0cb2a7
Create Date: 2024-09-21 19:42:12.685277

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f40098cf7022"
down_revision = "87329d0cb2a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("created_dt", sa.DateTime(), nullable=True))
    op.drop_constraint("teams_created_by_fkey", "teams", type_="foreignkey")
    op.drop_column("teams", "created_by")
    op.drop_column("teams", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "teams", sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "teams_created_by_fkey", "teams", "users", ["created_by"], ["id"]
    )
    op.drop_column("teams", "created_dt")
    # ### end Alembic commands ###
