"""empty message

Revision ID: cdc83dc9f4ad
Revises: ff1869599da0
Create Date: 2024-09-02 23:15:32.849289

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdc83dc9f4ad"
down_revision = "ff1869599da0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "is_alive")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column("is_alive", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
