"""empty message

Revision ID: 8693db54618c
Revises: a3f370983919
Create Date: 2024-09-21 19:50:02.051695

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8693db54618c"
down_revision = "a3f370983919"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("status_id", sa.Integer(), nullable=False))
    op.drop_column("teams", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column("status", sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    )
    op.drop_column("teams", "status_id")
    # ### end Alembic commands ###
