"""empty message

Revision ID: 6605c307f8ae
Revises: e1331a46cb08
Create Date: 2024-09-04 22:18:27.304276

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6605c307f8ae"
down_revision = "e1331a46cb08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
