"""empty message

Revision ID: a73f290059b9
Revises: f40098cf7022
Create Date: 2024-09-21 19:45:28.436403

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a73f290059b9"
down_revision = "f40098cf7022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
