"""empty message

Revision ID: e1331a46cb08
Revises: b4c1833615bf
Create Date: 2024-09-04 21:49:17.120787

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1331a46cb08"
down_revision = "b4c1833615bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_verification_codes",
        sa.Column("email", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_verification_codes", "email")
    # ### end Alembic commands ###
