"""empty message

Revision ID: 238bf7f5b1e6
Revises: eb41edfa3562
Create Date: 2024-08-31 23:01:52.823170

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "238bf7f5b1e6"
down_revision = "eb41edfa3562"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
